version: '3.8'
services:
  nginx:
    restart: always
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${IMAGE_NAME_ROOT}:${IMAGE_NAME_ROOT_VERSION}
    ports:
      - '80:80'
    depends_on:
      - not-too-powerful
    networks:
      - app-network

  not-too-powerful:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${IMAGE_NAME_4000}:${IMAGE_NAME_ROOT_VERSION}
    environment:
      - PORT
      - CLIENT_TOKEN
      - CLIENT_ID
      - CLIENT_SECRET
      - REDIRECT_URI
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
