- hosts: my_host
  become: true

  tasks:
    - name: Install awscli if not installed
      become: true
      apt:
        name: awscli
        state: latest
        update_cache: yes
      register: awscli_installed
      changed_when: awscli_installed.changed

    - name: Install Docker if not installed
      become: true
      apt:
        name: docker.io
        state: latest
        update_cache: yes
      register: docker_installed
      changed_when: docker_installed.changed

    - name: Install Docker Compose if not installed
      become: true
      shell: >
        test -n "$(docker-compose --version 2>/dev/null)" || 
        { sudo curl -sL "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose &&
        sudo chmod +x /usr/local/bin/docker-compose; }
      register: docker_compose_installed
      changed_when: docker_compose_installed.changed

    - name: Install pip if not installed
      become: true
      apt:
        name: python3-pip
        state: latest
        update_cache: yes
      register: pip_installed
      changed_when: pip_installed.changed

    - name: Install boto3 if not installed
      become: true
      pip:
        name: boto3
        state: latest
      register: boto3_installed
      changed_when: boto3_installed.changed

    - name: Print package versions
      shell: |
        aws --version
        docker --version
        docker-compose --version
        pip --version
        pip show boto3
      when:
        - awscli_installed.changed or docker_installed.changed or docker_compose_installed.changed
