set -e

AWS_REGION=$1
AWS_ACCOUNT_ID=$2
IMAGE_NAME_4000=$3
IMAGE_NAME_ROOT_VERSION=$4
VITE_DISCORD_GET_USER_CODE=$5
VITE_DISCORD_ADD_BOT_TO_SERVER=$6
VITE_API_BASE=$7

aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com

docker buildx build \
-t ${IMAGE_NAME_4000} \
--build-arg "VITE_DISCORD_GET_USER_CODE=${VITE_DISCORD_GET_USER_CODE}" \
--build-arg "VITE_DISCORD_ADD_BOT_TO_SERVER=${VITE_DISCORD_ADD_BOT_TO_SERVER}" \
--build-arg "VITE_API_BASE=${VITE_API_BASE}" .

docker tag ${IMAGE_NAME_4000}:${IMAGE_NAME_ROOT_VERSION} ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${IMAGE_NAME_4000}:${IMAGE_NAME_ROOT_VERSION}

docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${IMAGE_NAME_4000}:${IMAGE_NAME_ROOT_VERSION}
