service: not-too-powerful-discord-images
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    CLIENT_ID: ${file(./.env.${opt:stage, 'dev'}.json):CLIENT_ID}
    CLIENT_SECRET: ${file(./.env.${opt:stage, 'dev'}.json):CLIENT_SECRET}
    REDIRECT_URI: ${file(./.env.${opt:stage, 'dev'}.json):REDIRECT_URI}
    CLIENT_TOKEN: ${file(./.env.${opt:stage, 'dev'}.json):CLIENT_TOKEN}
  layers:
    - arn:aws:lambda:us-east-1:355738159777:layer:layerHelpers:4
  apiGateway:
    binaryMediaTypes:
      - 'multipart/form-data'

functions:
  sendImageMessage:
    handler: handler.sendImageMessageHandler
    events:
      - http:
          path: /sendImageMessage
          method: POST
          cors:
            origin: '*'
            headers:
              - Content-Type
              - Accept

custom:
  esbuild:
    bundle: true
    minify: false
    external:
      - 'helpers'
      - sharp
    packagerOptions:
      scripts:
        - npm install --arch=x64 --platform=linux sharp

  serverless-offline:
    useDocker: true

plugins:
  - serverless-esbuild
  - serverless-offline
