parser: '@typescript-eslint/parser'
parserOptions:
  # project: ./tsconfig.json
  tsconfigRootDir: "./api/auth"
root: true

ignorePatterns:
  - esbuild.js
  - dist/*

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:@typescript-eslint/strict
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:prettier/recommended
  - prettier

plugins:
  - '@typescript-eslint'
  - log
  - import
  - prettier

settings:
  import/resolver:
    typescript: true
    node: true

rules:
  prettier/prettier: error
  '@typescript-eslint/require-await': 0
  import/order:
    - error
    - newlines-between: always
      groups:
        - builtin
        - external
        - internal
        - unknown
        - parent
        - sibling
        - index
        - type
