service: not-too-powerful-discord-guilds
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    CLIENT_ID: ${file(./.env.${opt:stage, 'dev'}.json):CLIENT_ID}
    CLIENT_SECRET: ${file(./.env.${opt:stage, 'dev'}.json):CLIENT_SECRET}
    REDIRECT_URI: ${file(./.env.${opt:stage, 'dev'}.json):REDIRECT_URI}
    CLIENT_TOKEN: ${file(./.env.${opt:stage, 'dev'}.json):CLIENT_TOKEN}
  layers:
    - arn:aws:lambda:us-east-1:355738159777:layer:layerHelpers:4

functions:
  getBotMatchesHandler:
    handler: handler.getBotMatchesHandler
    events:
      - httpApi:
          path: /getBotMatches
          method: GET
  # handler:
  #   handler: handler.handler
  #   events:
  #     - httpApi:
  #         path: /{proxy+}
  #         method: ANY

custom:
  esbuild:
    bundle: true
    minify: false
    external:
      - 'helpers'
  serverless-offline:
    useDocker: true

plugins:
  - serverless-esbuild
  - serverless-offline
