name: Deploy to Amazon ECS

on:
   push:
     branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install yarn

    - name: Generate client env
      run: |
        touch client/.env
        echo "VITE_DISCORD_GET_USER_CODE=${{ secrets.VITE_DISCORD_GET_USER_CODE }}" >> client/.env
        echo "VITE_DISCORD_ADD_BOT_TO_SERVER=${{ secrets.VITE_DISCORD_ADD_BOT_TO_SERVER }}" >> client/.env
        echo "VITE_API_BASE=${{ secrets.VITE_API_BASE }}" >> client/.env
 
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Run Bash
      run: bash deploy.sh
