name: Deploy to VM

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy application/Run playbook
        uses: dawidd6/action-ansible-playbook@v2.6.1
        with:
          playbook: playbook_pull_and_compose.yml     
          directory: ./
          key: ${{secrets.SSH_PRIVATE_KEY}}
          options: |
            --inventory inventory_production.yml
            --extra-vars "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }} aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }} aws_region=${{ secrets.AWS_REGION }} aws_account_id=${{ secrets.AWS_ACCOUNT_ID }} compose_item=${{ secrets.COMPOSE_ITEM }} CLIENT_TOKEN=${{ secrets.CLIENT_TOKEN }} PORT=${{ secrets.PORT }} CLIENT_TOKEN=${{ secrets.CLIENT_TOKEN }} CLIENT_ID=${{ secrets.CLIENT_ID }} CLIENT_SECRET=${{ secrets.CLIENT_SECRET }} REDIRECT_URI=${{ secrets.REDIRECT_URI }}"